const statusElement=document.getElementById("status");
const nf=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:4});
let firstTableSnapshot=null;

Office.onReady((info)=>{
  if(info.host!==Office.HostType.Excel){setStatus("Откройте надстройку в Excel.",true);return;}
  document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>openPanel(b.dataset.panel)));
  bind("analyze-selection",analyzeSelection);bind("preview-cleaning",()=>cleanSelection(false));bind("apply-cleaning",()=>cleanSelection(true));
  bind("highlight-duplicates",highlightDuplicates);bind("remove-duplicates",removeDuplicates);
  bind("save-first-range",saveFirstRange);bind("compare-second-range",compareSecondRange);bind("create-report",createReport);
  setStatus("Готово.");
});

function bind(id,fn){document.getElementById(id).addEventListener("click",fn);}
function openPanel(name){document.querySelectorAll(".tab,.panel").forEach(e=>e.classList.remove("active"));document.querySelector(`[data-panel="${name}"]`).classList.add("active");document.getElementById(`panel-${name}`).classList.add("active");}

async function analyzeSelection(){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values","valueTypes","rowCount","columnCount"]);await c.sync();const v=r.values.flat(),t=r.valueTypes.flat();const nums=v.filter((x,i)=>t[i]===Excel.RangeValueType.double&&Number.isFinite(x));const empty=v.filter((x,i)=>t[i]===Excel.RangeValueType.empty||x===""||x===null).length;const errors=t.filter(x=>x===Excel.RangeValueType.error).length;const filled=v.filter((_x,i)=>t[i]!==Excel.RangeValueType.empty);const sorted=[...nums].sort((a,b)=>a-b),sum=nums.reduce((a,b)=>a+b,0);const stats={sum:nums.length?sum:null,average:nums.length?sum/nums.length:null,median:median(sorted),min:nums.length?sorted[0]:null,max:nums.length?sorted.at(-1):null,numbers:nums.length,filled:filled.length,empty,unique:new Set(filled.map(uniqueKey)).size,errors};Object.entries(stats).forEach(([k,x])=>document.getElementById(`metric-${k}`).textContent=x===null?"—":nf.format(x));document.getElementById("analysis-address").textContent=r.address;document.getElementById("analysis-size").textContent=`${r.rowCount} × ${r.columnCount} · ${v.length} ячеек`;document.getElementById("analysis-results").classList.remove("hidden");setStatus(`Диапазон ${r.address} проанализирован.`);});}

async function cleanSelection(apply){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values","rowCount","columnCount"]);await c.sync();const original=r.values,cleaned=original.map(row=>row.map(cleanValue));const removeEmpty=document.getElementById("clean-empty-rows").checked;const finalValues=removeEmpty?cleaned.filter(row=>row.some(v=>v!==""&&v!==null)):cleaned;let changed=0;original.forEach((row,i)=>row.forEach((v,j)=>{if(String(v)!==String(cleaned[i][j]))changed++;}));const removed=original.length-finalValues.length;showResult("clean-preview",`Изменяемых ячеек: ${changed}\nПолностью пустых строк: ${removed}\nДиапазон: ${r.address}`);if(!apply){setStatus("Предварительный просмотр готов.");return;}const backup=await backupRange(c,r,"Резерв_очистка");r.clear("Contents");if(finalValues.length){const target=r.getCell(0,0).getResizedRange(finalValues.length-1,r.columnCount-1);target.values=finalValues;}await c.sync();showResult("clean-preview",`Очистка завершена. Изменено: ${changed}; удалено пустых строк: ${removed}.\nРезервная копия: ${backup}`);setStatus("Данные очищены.");});}
function cleanValue(v){if(typeof v!=="string")return v;let x=v;if(document.getElementById("clean-nonprinting").checked)x=x.replace(/[\x00-\x1F\x7F]/g,"");if(document.getElementById("clean-trim").checked)x=x.replace(/\s+/g," ").trim();const mode=document.getElementById("clean-case").value;if(mode==="upper")x=x.toLocaleUpperCase("ru-RU");if(mode==="lower")x=x.toLocaleLowerCase("ru-RU");if(mode==="title")x=x.toLocaleLowerCase("ru-RU").replace(/(^|\s)\p{L}/gu,m=>m.toLocaleUpperCase("ru-RU"));return x;}

async function highlightDuplicates(){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values","rowCount"]);await c.sync();const seen=new Set(),dupes=[];r.values.forEach((row,i)=>{const k=rowKey(row);if(seen.has(k))dupes.push(i);else seen.add(k);});for(const i of dupes)r.getRow(i).format.fill.color="#FFD966";await c.sync();showResult("duplicate-result",`Найдено и подсвечено повторных строк: ${dupes.length}`);setStatus("Проверка дубликатов завершена.");});}
async function removeDuplicates(){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values","columnCount","rowCount"]);await c.sync();const seen=new Set(),unique=[];for(const row of r.values){const k=rowKey(row);if(!seen.has(k)){seen.add(k);unique.push(row);}}const removed=r.values.length-unique.length;const backup=await backupRange(c,r,"Резерв_дубликаты");r.clear("Contents");if(unique.length)r.getCell(0,0).getResizedRange(unique.length-1,r.columnCount-1).values=unique;await c.sync();showResult("duplicate-result",`Удалено повторных строк: ${removed}\nРезервная копия: ${backup}`);setStatus("Дубликаты удалены.");});}

async function saveFirstRange(){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values"]);await c.sync();firstTableSnapshot={address:r.address,values:r.values};showResult("compare-result",`Первая таблица сохранена: ${r.address}\nСтрок данных: ${Math.max(0,r.values.length-1)}`);setStatus("Первая таблица сохранена.");});}
async function compareSecondRange(){if(!firstTableSnapshot){setStatus("Сначала сохраните первую таблицу.",true);return;}await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values"]);await c.sync();const a=firstTableSnapshot.values,b=r.values;if(a.length<2||b.length<2)throw new Error("Обе таблицы должны содержать заголовок и данные.");const width=Math.max(a[0].length,b[0].length),mapA=new Map(a.slice(1).map(row=>[uniqueKey(row[0]),row])),mapB=new Map(b.slice(1).map(row=>[uniqueKey(row[0]),row]));const rows=[["Статус","Ключ",...Array.from({length:width},(_,i)=>`Таблица 1: ${a[0][i]??`Столбец ${i+1}`}`),...Array.from({length:width},(_,i)=>`Таблица 2: ${b[0][i]??`Столбец ${i+1}`}`)]];for(const [k,rowA] of mapA){const rowB=mapB.get(k);rows.push([!rowB?"Только в первой":rowKey(rowA)===rowKey(rowB)?"Совпадает":"Изменено",rowA[0],...pad(rowA,width),...pad(rowB||[],width)]);}for(const [k,rowB] of mapB)if(!mapA.has(k))rows.push(["Только во второй",rowB[0],...pad([],width),...pad(rowB,width)]);const ws=c.workbook.worksheets.add(safeSheetName("Сверка"));ws.load("name");const out=ws.getRangeByIndexes(0,0,rows.length,rows[0].length);out.values=rows;out.getRow(0).format.fill.color="#217346";out.getRow(0).format.font.color="#FFFFFF";out.getRow(0).format.font.bold=true;out.format.autofitColumns();ws.activate();await c.sync();const counts=rows.slice(1).reduce((o,row)=>(o[row[0]]=(o[row[0]]||0)+1,o),{});showResult("compare-result",Object.entries(counts).map(([k,v])=>`${k}: ${v}`).join("\n")+`\nРезультат: ${ws.name}`);setStatus("Сверка завершена.");});}

async function createReport(){await run(async c=>{const r=c.workbook.getSelectedRange();r.load(["address","values","rowCount","columnCount"]);await c.sync();if(r.rowCount<2)throw new Error("Выделите таблицу с заголовком и строками данных.");const headers=r.values[0],data=r.values.slice(1),rows=[["Показатель","Значение"],["Источник",r.address],["Строк данных",data.length],["Столбцов",r.columnCount],["Пустых ячеек",data.flat().filter(v=>v===""||v===null).length]];const numericSummary=[];headers.forEach((h,i)=>{const nums=data.map(row=>row[i]).filter(v=>typeof v==="number"&&Number.isFinite(v));if(nums.length){const sum=nums.reduce((a,b)=>a+b,0);numericSummary.push([String(h||`Столбец ${i+1}`),nums.length,sum,sum/nums.length,Math.min(...nums),Math.max(...nums)]);}});const ws=c.workbook.worksheets.add(safeSheetName("Отчёт"));ws.load("name");ws.getRangeByIndexes(0,0,rows.length,2).values=rows;const start=rows.length+2;const tableRows=[["Числовой столбец","Количество","Сумма","Среднее","Минимум","Максимум"],...numericSummary];ws.getRangeByIndexes(start,0,tableRows.length,6).values=tableRows;ws.getRangeByIndexes(0,0,1,2).format.fill.color="#217346";ws.getRangeByIndexes(start,0,1,6).format.fill.color="#217346";ws.getRangeByIndexes(0,0,1,2).format.font.color="#FFFFFF";ws.getRangeByIndexes(start,0,1,6).format.font.color="#FFFFFF";if(numericSummary.length){const chart=ws.charts.add("ColumnClustered",ws.getRangeByIndexes(start,0,tableRows.length,3));chart.title.text="Суммы по числовым столбцам";chart.setPosition("H2","P18");}ws.getUsedRange().format.autofitColumns();ws.activate();await c.sync();showResult("report-result",`Отчёт создан: ${ws.name}\nЧисловых столбцов: ${numericSummary.length}`);setStatus("Отчёт создан.");});}

async function backupRange(c,r,prefix){const ws=c.workbook.worksheets.add(safeSheetName(prefix));ws.load("name");const copy=ws.getRangeByIndexes(0,0,r.rowCount,r.columnCount);copy.copyFrom(r,"All");await c.sync();return ws.name;}
function safeSheetName(prefix){const stamp=new Date().toISOString().slice(11,23).replace(/[:.]/g,"");return `${prefix}_${stamp}`.slice(0,31);}
function rowKey(row){return JSON.stringify(row.map(uniqueKey));}function uniqueKey(v){return typeof v==="string"?`s:${v.trim().toLocaleLowerCase("ru-RU")}`:`${typeof v}:${String(v)}`;}function pad(row,n){return Array.from({length:n},(_,i)=>row[i]??"");}
function median(a){if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function showResult(id,text){const e=document.getElementById(id);e.textContent=text;e.classList.remove("hidden");}
async function run(action){toggle(true);try{await Excel.run(action);}catch(e){console.error(e);setStatus(e.message||"Ошибка Excel.",true);}finally{toggle(false);}}
function setStatus(m,error=false){statusElement.textContent=m;statusElement.classList.toggle("error",error);}function toggle(v){document.querySelectorAll("button").forEach(b=>b.disabled=v);}
